/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.29).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.CDSRequest;
import io.swagger.model.CDSResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2023-01-27T10:43:47.246Z")

@Api(value = "cds-services", description = "the cds-services API")
@RequestMapping(value = "")
@RestController
@CrossOrigin
public interface CdsServicesApi {
    Logger logger = LoggerFactory.getLogger(CdsServicesApi.class);

    /**
     * Interface function for catching incoming calls.
     * WARNING: This is a example interface function for the orientation to create own version of rest interfaces.
     *          Pls delete after you created your own rest interface.
     *
     * @param request The request body itself
     * @param token The authentication token for hapi fhir oder ongoing request on a remote fhir server.
     * @param headers Header information about the request itself.
     * @return A created CDSResponse object for the requester.
     */
    @CrossOrigin
    @ApiOperation(value = "", nickname = "suggestionToPatientAStudy", notes = "Invoke a CDS service offered by this CDS Provider", response = CDSResponse.class, tags = {})
    @ApiResponses(value = {@ApiResponse(code = 200, message = "Success (includes CDS Cards)", response = CDSResponse.class)})
    @RequestMapping(value = "/cds-services/template", produces = {"application/json"}, consumes = {"application/json"}, method = RequestMethod.POST)      // , @RequestHeader(name = "Authorization") String token
    public ResponseEntity<CDSResponse> cdsTestService(@ApiParam(value = "Body of CDS service request", required = true) @Valid @RequestBody CDSRequest request, @RequestHeader Map<String, String> headers);

}
